# Generated by Django 4.0.2 on 2022-02-02 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='date_added',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='account',
            name='broker',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.TextField(default='USD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='equity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='free_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='leverage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='login_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='stopout_level_format',
            field=models.CharField(choices=[('p', 'percentage'), ('c', 'currency')], default='p', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='trade_server',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('d', 'demo'), ('c', 'competition'), ('r', 'real')], default='d', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='close_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 13, 29, 260754, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='lots',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='magic_number',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='open_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='open_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 15, 13, 49, 15970, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='swap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='ticket_number',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='pips',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
