# Generated by Django 4.0.2 on 2022-02-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_remove_trade_date_added_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='margin_call_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='margin_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='margin_stopout_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='stopout_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='stopout_level_format',
            field=models.CharField(choices=[('p', 'percentage'), ('m', 'money')], max_length=10),
        ),
    ]
