# Generated by Django 4.0.2 on 2022-02-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_account_margin_call_level_account_margin_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='entry_date',
            field=models.DateField(null=True),
        ),
    ]
