# Generated by Django 4.0.2 on 2022-02-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0008_remove_deposit_date_remove_withdrawal_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='ticket_number',
            new_name='trade_id',
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
