# Generated by Django 4.0.2 on 2022-02-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_rename_ticket_number_trade_trade_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deposit',
            unique_together={('account', 'deposit_id')},
        ),
        migrations.AlterUniqueTogether(
            name='withdrawal',
            unique_together={('account', 'withdrawal_id')},
        ),
    ]
