# Generated by Django 4.0.2 on 2022-02-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_alter_deposit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together={('account', 'trade_id')},
        ),
    ]
