# Generated by Django 4.0.2 on 2022-02-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0018_remove_account_stopout_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='lots',
        ),
    ]
