# Generated by Django 4.0.2 on 2022-03-08 19:13

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0023_unknowntransaction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ('time',)},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ('close_time',)},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ('time',)},
        ),
        migrations.AddField(
            model_name='unknowntransaction',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='action',
            field=models.CharField(max_length=50),
        )
    ]
