# Generated by Django 4.0.3 on 2022-03-15 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0026_metaapierror'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='trader_no_duplicate_account',
        ),
        migrations.RemoveConstraint(
            model_name='unknowntransaction',
            name='trader_no_duplicate_unknown_transaction',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='trade_server',
            new_name='server',
        ),
        migrations.RemoveField(
            model_name='account',
            name='login_number',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin_call_level',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin_level',
        ),
        migrations.RemoveField(
            model_name='account',
            name='margin_stopout_level',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profit_loss',
        ),
        migrations.RemoveField(
            model_name='account',
            name='stopout_level_format',
        ),
        migrations.RemoveField(
            model_name='unknowntransaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='account',
            name='investor_mode',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='login',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='margin_mode',
            field=models.CharField(default='ACCOUNT_MARGIN_MODE_RETAIL_HEDGING', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.CharField(choices=[('mt4', 'mt4'), ('mt5', 'mt5')], default='mt4', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='trade_allowed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='unknowntransaction',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('login', 'user'), name='trader_no_duplicate_account'),
        ),
    ]
