# Generated by Django 4.0.3 on 2022-03-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0027_remove_account_trader_no_duplicate_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='entry_image',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='entry_image_link',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='exit_date',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='exit_image',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='exit_image_link',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='pips',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='risk_reward_ratio',
        ),
        migrations.AddField(
            model_name='deposit',
            name='broker_time',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='reason',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='broker_time',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='action',
            field=models.CharField(max_length=10),
        ),
    ]
