# Generated by Django 4.0.3 on 2022-03-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0028_remove_trade_comment_remove_trade_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.IntegerField(),
        ),
    ]
