# Generated by Django 4.0.3 on 2022-03-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0031_account_volume_trade_broker_close_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='volume',
        ),
        migrations.AddField(
            model_name='trade',
            name='volume',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=19),
            preserve_default=False,
        ),
    ]
