# Generated by Django 4.0.3 on 2022-03-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0033_rename_magic_number_trade_magic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.PositiveIntegerField(),
        ),
    ]
