# Generated by Django 4.0.3 on 2022-03-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0034_alter_account_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.PositiveBigIntegerField(),
        ),
    ]
