# Generated by Django 4.0.3 on 2022-04-03 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0035_alter_account_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
