# Generated by Django 4.0.3 on 2022-04-05 13:42

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_traderinfo_last_data_refresh_time'),
        ('trader', '0039_unresolvedrefreshaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshAccountError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trader')),
            ],
        ),
    ]
