# Generated by Django 4.0.3 on 2022-04-05 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0041_unresolvedremoveaccount_removeaccounterror'),
    ]

    operations = [
        migrations.AddField(
            model_name='removeaccounterror',
            name='account',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='trader.account'),
            preserve_default=False,
        ),
    ]
