# Generated by Django 4.0.4 on 2022-05-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0044_unresolvedaddaccount_broker_info_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unresolvedaddaccount',
            name='broker_info_content',
            field=models.BinaryField(null=True),
        ),
    ]
