# Generated by Django 4.0.4 on 2022-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0046_alter_unresolvedaddaccount_broker_info_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unresolvedaddaccount',
            name='broker_info_content',
            field=models.BinaryField(null=True),
        ),
    ]
