# Generated by Django 4.0.5 on 2022-06-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0048_unresolveddeployaccount_deployaccounterror'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deployed',
            field=models.BooleanField(default=True),
        ),
    ]
