# Generated by Django 4.0 on 2022-01-02 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='DeleteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.account')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('b', 'Buy'), ('s', 'Sell')], max_length=4)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('risk_reward_ratio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=11)),
                ('pips', models.DecimalField(decimal_places=2, max_digits=7)),
                ('notes', models.TextField(blank=True, null=True)),
                ('entry_image_link', models.URLField(blank=True, null=True)),
                ('exit_image_link', models.URLField(blank=True, null=True)),
                ('entry_image', models.ImageField(null=True, upload_to='')),
                ('exit_image', models.ImageField(null=True, upload_to='')),
                ('date_added', models.DateField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.account')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.account')),
            ],
        ),
    ]
