# Generated by Django 4.0.2 on 2022-02-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_alter_trade_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='risk_reward_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
