# Generated by Django 4.0.2 on 2022-02-04 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0007_alter_trade_magic_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='date',
        ),
        migrations.AddField(
            model_name='deposit',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 19, 1, 46, 74351, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 19, 2, 0, 183020, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
