# Generated by Django 4.0.2 on 2022-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0011_alter_deposit_deposit_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deposit',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='withdrawal',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.UniqueConstraint(fields=('account', 'deposit_id'), name='trader_no_duplicate_deposit'),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('account', 'trade_id'), name='trader_no_duplicate_trade'),
        ),
        migrations.AddConstraint(
            model_name='withdrawal',
            constraint=models.UniqueConstraint(fields=('account', 'withdrawal_id'), name='trader_no_duplicate_withdrawal'),
        ),
    ]
