# Generated by Django 4.0.2 on 2022-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0012_alter_deposit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
