# Generated by Django 4.0.2 on 2022-02-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0015_alter_preferences_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='current_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trader.account'),
        ),
    ]
