# Generated by Django 4.0.2 on 2022-02-15 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_trader'),
        ('trader', '0016_alter_preferences_current_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('d', 'demo'), ('c', 'contest'), ('r', 'real')], max_length=10),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.trader'),
        ),
    ]
