# Generated by Django 4.0.2 on 2022-02-18 11:14

from django.db import migrations
import trader.models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0021_alter_account_login_number_alter_deposit_deposit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login_number',
            field=trader.models.TransactionIdField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_id',
            field=trader.models.TransactionIdField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=trader.models.TransactionIdField(max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_id',
            field=trader.models.TransactionIdField(max_length=100),
        ),
    ]
