# Generated by Django 3.2.7 on 2021-09-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_endpoint', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionInfo',
        ),
    ]
