# Generated by Django 3.2.7 on 2021-10-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='unsubscribed_users',
            field=models.IntegerField(null=True),
        ),
    ]
