# Generated by Django 4.0.2 on 2022-02-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FailedPayout',
        ),
    ]
