# Generated by Django 4.0.5 on 2022-06-13 15:07

import django.core.serializers.json
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterwaveError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err_type', models.CharField(max_length=100)),
                ('err_data', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
