import { MONTHLY_PLAN_PRICE, YEARLY_PLAN_PRICE, WBA_PLAN_PRICE } from "@apps/trader-app/const";


const YEARLY_PLAN_ID: string = '75837';
const MONTHLY_PLAN_ID: string = '75836';
const WBA_PLAN_ID: string = '75838';
const FLUTTERWAVE_PUBLIC_KEY: string = 'FLWPUBK-9155d7d07e24f30b241c35a031911e01-X'

export {
    MONTHLY_PLAN_PRICE,
    YEARLY_PLAN_PRICE,
    WBA_PLAN_PRICE,
    YEARLY_PLAN_ID,
    MONTHLY_PLAN_ID,
    WBA_PLAN_ID,
    FLUTTERWAVE_PUBLIC_KEY,

}