const NAVBAR_WIDTH = 270;
const MONTHLY_PLAN_PRICE = 19.95;
const YEARLY_PLAN_PRICE = 199.95;
const WBA_PLAN_PRICE = 150.00;
const AFFILIATE_WBA_USERNAME = 'wba';


export {
    NAVBAR_WIDTH,
    MONTHLY_PLAN_PRICE,
    YEARLY_PLAN_PRICE,
    WBA_PLAN_PRICE,
    AFFILIATE_WBA_USERNAME
}