# Generated by Django 4.0.2 on 2022-02-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_traderinfo_datasource_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderinfo',
            name='datasource_username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
