# Generated by Django 4.0.2 on 2022-02-12 03:26

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_traderinfo_datasource_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', users.models.TraderManager()),
            ],
        ),
    ]
