# Generated by Django 3.2.7 on 2021-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscriptioninfo_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='payment_method',
            field=models.CharField(choices=[('pp', 'paypal'), ('ps', 'paystack')], max_length=5, null=True),
        ),
    ]
