# Generated by Django 3.2.7 on 2021-09-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscriptioninfo_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=128)),
                ('paypal_email', models.EmailField(max_length=254)),
                ('subscription_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.subscriptioninfo')),
            ],
        ),
    ]
