# Generated by Django 3.2.7 on 2021-10-01 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_paypalsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninfo',
            name='last_payed',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptioninfo',
            name='on_free',
            field=models.BooleanField(default=True),
        ),
    ]
