# Generated by Django 3.2.7 on 2021-10-01 16:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
        ('users', '0006_auto_20211001_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalsubscription',
            name='paypal_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='last_payed',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='referrer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.affiliate'),
        ),
    ]
