# Generated by Django 3.2.7 on 2021-10-02 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211001_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalsubscription',
            name='next_billing_time',
            field=models.DateField(default=datetime.date(2021, 10, 2)),
            preserve_default=False,
        ),
    ]
