# Generated by Django 3.2.7 on 2021-10-03 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211002_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalsubscription',
            name='next_billing_time',
        ),
        migrations.RemoveField(
            model_name='subscriptioninfo',
            name='last_payed',
        ),
        migrations.AddField(
            model_name='subscriptioninfo',
            name='next_billing_time',
            field=models.DateField(default=datetime.date(2021, 11, 3)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paystacksubscription',
            name='reference',
            field=models.CharField(max_length=50),
        ),
    ]
