# Generated by Django 3.2.7 on 2021-10-03 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211003_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalsubscription',
            name='next_billing_time',
            field=models.DateField(default=datetime.date(2021, 11, 3)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptioninfo',
            name='last_payed',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
