# Generated by Django 3.2.7 on 2021-10-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_auto_20211007_0857'),
        ('users', '0014_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='referrer',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.affiliate'),
        ),
    ]
