# Generated by Django 3.2.8 on 2021-11-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userinfo_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='current_feedback_question',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='logins_after_ask',
            field=models.SmallIntegerField(null=True),
        ),
    ]
