# Generated by Django 3.2.8 on 2021-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20211112_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_feedback_question', models.SmallIntegerField(default=0)),
                ('logins_after_ask', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='current_feedback_question',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='logins_after_ask',
        ),
    ]
