# Generated by Django 4.0.1 on 2022-01-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_traderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderinfo',
            name='how_you_heard_about_us',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderinfo',
            name='trading_time_before_joining',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
