# Generated by Django 4.0.2 on 2022-02-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_trader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderinfo',
            name='datasource_username',
        ),
        migrations.CreateModel(
            name='DatasourceUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('traderinfo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.traderinfo')),
            ],
        ),
    ]
