# Generated by Django 4.0.2 on 2022-02-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_traderinfo_datasource_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailChimpError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('action', models.CharField(max_length=20)),
            ],
        ),
    ]
