# Generated by Django 4.0.3 on 2022-04-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mailchimperror'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderinfo',
            name='last_data_refresh_time',
            field=models.DateTimeField(null=True),
        ),
    ]
