# Generated by Django 4.0.5 on 2022-06-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_traderinfo_last_data_refresh_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninfo',
            name='last_billed_time',
            field=models.DateField(null=True),
        ),
    ]
