# Generated by Django 4.0.5 on 2022-06-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_subscriptioninfo_last_billed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninfo',
            name='subscription_plan',
            field=models.CharField(choices=[('m', 'monthly')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='payment_method',
            field=models.CharField(choices=[('pp', 'paypal'), ('ps', 'paystack'), ('fl', 'flutterwave')], max_length=5, null=True),
        ),
    ]
