# Generated by Django 4.0.5 on 2022-06-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_subscriptioninfo_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='subscription_plan',
            field=models.CharField(choices=[('m', 'monthly'), ('y', 'yearly')], max_length=5, null=True),
        ),
    ]
