# Generated by Django 4.0.5 on 2022-08-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_subscriptioninfo_time_of_free_trial_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='amount_earned',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='next_payout',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='payment_email',
        ),
    ]
