# Generated by Django 4.0.5 on 2022-08-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_affiliate_bank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='referrer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.affiliate'),
        ),
    ]
