# Generated by Django 4.0.5 on 2022-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_subscriptioninfo_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='bank_account_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptioninfo',
            name='subscription_plan',
            field=models.CharField(choices=[('m', 'monthly'), ('y', 'yearly'), ('w', 'wba-yearly')], max_length=5, null=True),
        ),
    ]
