# Generated by Django 4.0.5 on 2022-08-26 08:33

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_affiliate_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='bank_account_number',
            field=users.models.IntegerAsCharField(max_length=50, null=True),
        ),
    ]
