# Generated by Django 4.0.5 on 2022-09-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_affiliate_bank_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderinfo',
            name='post_account_connect_mailchimp_journey_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
